// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the ComputeContacts method.
public struct ComputeContactsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the resource to compute contacts for.
  /// Format: organizations/{organization_id},
  /// folders/{folder_id} or projects/{project_id}
  public var parent: Swift.String = Swift.String()

  /// The categories of notifications to compute contacts for. If ALL is included
  /// in this list, contacts subscribed to any notification category will be
  /// returned.
  public var notificationCategories: [NotificationCategory] = []

  /// Optional. The maximum number of results to return from this request.
  /// Non-positive values are ignored. The presence of `next_page_token` in the
  /// response indicates that more results might be available.
  /// If not specified, the default page_size is 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. If present, retrieves the next batch of results from the
  /// preceding call to this method. `page_token` must be the value of
  /// `next_page_token` from the previous response. The values of other method
  /// parameters should be identical to those in the previous call.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ComputeContactsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeContactsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.essentialcontacts.v1.ComputeContactsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
