// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A contact that will receive notifications from Google Cloud.
public struct Contact: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The identifier for the contact.
  /// Format: {resource_type}/{resource_id}/contacts/{contact_id}
  public var name: Swift.String = Swift.String()

  /// Required. The email address to send notifications to. The email address
  /// does not need to be a Google Account.
  public var email: Swift.String = Swift.String()

  /// Required. The categories of notifications that the contact will receive
  /// communications for.
  public var notificationCategorySubscriptions: [NotificationCategory] = []

  /// Required. The preferred language for notifications, as a ISO 639-1 language
  /// code. See [Supported
  /// languages](https://cloud.google.com/resource-manager/docs/managing-notification-contacts#supported-languages)
  /// for a list of supported languages.
  public var languageTag: Swift.String = Swift.String()

  /// Output only. The validity of the contact. A contact is considered valid if
  /// it is the correct recipient for notifications for a particular resource.
  public var validationState: ValidationState = ValidationState()

  /// The last time the validation_state was updated, either manually or
  /// automatically. A contact is considered stale if its validation state was
  /// updated more than 1 year ago.
  public var validateTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Contact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Contact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let email = CodingKeys(stringValue: "email")
    static let notificationCategorySubscriptions = CodingKeys(
      stringValue: "notificationCategorySubscriptions")
    static let languageTag = CodingKeys(stringValue: "languageTag")
    static let validationState = CodingKeys(stringValue: "validationState")
    static let validateTime = CodingKeys(stringValue: "validateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "email",
      "notificationCategorySubscriptions",
      "languageTag",
      "validationState",
      "validateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .email) {
      self.email = value
    }
    if let value = try container.decodeIfPresent(
      [NotificationCategory].self, forKey: .notificationCategorySubscriptions)
    {
      self.notificationCategorySubscriptions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageTag) {
      self.languageTag = value
    }
    if let value = try container.decodeIfPresent(ValidationState.self, forKey: .validationState) {
      self.validationState = value
    }
    self.validateTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .validateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.email, forKey: .email)
    try container.encode(
      self.notificationCategorySubscriptions, forKey: .notificationCategorySubscriptions)
    try container.encode(self.languageTag, forKey: .languageTag)
    try container.encode(self.validationState, forKey: .validationState)
    try container.encodeIfPresent(self.validateTime, forKey: .validateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.essentialcontacts.v1.Contact"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
