// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class EssentialContactsServiceRetry: EssentialContactsServiceStub {
    let inner: any EssentialContactsServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any EssentialContactsServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createContact(
      request: CreateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.createContact(request: r, options: o)
        })
    }

    public func updateContact(
      request: UpdateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.updateContact(request: r, options: o)
        })
    }

    public func listContacts(
      request: ListContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListContactsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.ListContactsResponse
          in
          return try await self.inner.listContacts(request: r, options: o)
        })
    }

    public func getContact(
      request: GetContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.getContact(request: r, options: o)
        })
    }

    public func deleteContact(
      request: DeleteContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteContactRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteContact(request: r, options: o)
        })
    }

    public func computeContacts(
      request: ComputeContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ComputeContactsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.ComputeContactsResponse
          in
          return try await self.inner.computeContacts(request: r, options: o)
        })
    }

    public func sendTestMessage(
      request: SendTestMessageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SendTestMessageRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.sendTestMessage(request: r, options: o)
        })
    }
  }
}
