// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class EssentialContactsServiceLogging: EssentialContactsServiceStub {
    let inner: any EssentialContactsServiceStub
    let logger: Logger

    public init(_ inner: any EssentialContactsServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-essentialcontacts-v1"
      logger[metadataKey: "gcp.client.service"] = "essentialcontacts"
      logger[metadataKey: "gcp.experimental.swift.client"] = "EssentialContactsService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createContact(
      request: CreateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        name: "createContact",
        action: {
          (r: CreateContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.createContact(request: r, options: o)
        })
    }

    public func updateContact(
      request: UpdateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateContact",
        action: {
          (r: UpdateContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.updateContact(request: r, options: o)
        })
    }

    public func listContacts(
      request: ListContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listContacts",
        action: {
          (r: ListContactsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.ListContactsResponse
          in
          return try await self.inner.listContacts(request: r, options: o)
        })
    }

    public func getContact(
      request: GetContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact {
      try await self._intercept(
        request: request,
        options: options,
        name: "getContact",
        action: {
          (r: GetContactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.Contact
          in
          return try await self.inner.getContact(request: r, options: o)
        })
    }

    public func deleteContact(
      request: DeleteContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteContact",
        action: {
          (r: DeleteContactRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteContact(request: r, options: o)
        })
    }

    public func computeContacts(
      request: ComputeContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "computeContacts",
        action: {
          (r: ComputeContactsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudEssentialContactsV1.ComputeContactsResponse
          in
          return try await self.inner.computeContacts(request: r, options: o)
        })
    }

    public func sendTestMessage(
      request: SendTestMessageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "sendTestMessage",
        action: {
          (r: SendTestMessageRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.sendTestMessage(request: r, options: o)
        })
    }
  }
}
