// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol EssentialContactsServiceStub {
    func createContact(
      request: CreateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    func updateContact(
      request: UpdateContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    func listContacts(
      request: ListContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse

    func getContact(
      request: GetContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    func deleteContact(
      request: DeleteContactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func computeContacts(
      request: ComputeContactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse

    func sendTestMessage(
      request: SendTestMessageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
