// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages contacts for important Google Cloud notifications.
///
/// @Snippet(path: "EssentialContactsServiceQuickstart")
public final class EssentialContactsServiceClient: Clients.EssentialContactsServiceProtocol,
  Sendable
{
  let inner: any Clients.EssentialContactsServiceStub

  /// Creates a new `EssentialContactsServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.EssentialContactsServiceStub =
      try Clients.EssentialContactsServiceTransport(options)
    inner = Clients.EssentialContactsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EssentialContactsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Adds a new contact for a resource.
  ///
  /// @Snippet(path: "EssentialContactsService_CreateContact")
  public func createContact(
    request: CreateContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    try await self.inner.createContact(request: request, options: options)
  }

  /// Updates a contact.
  /// Note: A contact's email address cannot be changed.
  ///
  /// @Snippet(path: "EssentialContactsService_UpdateContact")
  public func updateContact(
    request: UpdateContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    try await self.inner.updateContact(request: request, options: options)
  }

  /// Lists the contacts that have been set on a resource.
  ///
  /// @Snippet(path: "EssentialContactsService_ListContacts")
  public func listContacts(
    request: ListContactsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse {
    try await self.inner.listContacts(request: request, options: options)
  }

  /// Gets a single contact.
  ///
  /// @Snippet(path: "EssentialContactsService_GetContact")
  public func getContact(
    request: GetContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    try await self.inner.getContact(request: request, options: options)
  }

  /// Deletes a contact.
  ///
  /// @Snippet(path: "EssentialContactsService_DeleteContact")
  public func deleteContact(
    request: DeleteContactRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteContact(request: request, options: options)
  }

  /// Lists all contacts for the resource that are subscribed to the
  /// specified notification categories, including contacts inherited from
  /// any parent resources.
  ///
  /// @Snippet(path: "EssentialContactsService_ComputeContacts")
  public func computeContacts(
    request: ComputeContactsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse {
    try await self.inner.computeContacts(request: request, options: options)
  }

  /// Allows a contact admin to send a test message to contact to verify that it
  /// has been configured correctly.
  ///
  /// @Snippet(path: "EssentialContactsService_SendTestMessage")
  public func sendTestMessage(
    request: SendTestMessageRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.sendTestMessage(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EssentialContactsServiceClient`.
  ///
  /// To mock `EssentialContactsServiceClient` change your functions to receive
  /// `some EssentialContactsServiceProtocol` or `any EssentialContactsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EssentialContactsServiceProtocol: Sendable {
    /// See `EssentialContactsServiceClient.createContact`.
    func createContact(
      request: CreateContactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    /// See `EssentialContactsServiceClient.updateContact`.
    func updateContact(
      request: UpdateContactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    /// See `EssentialContactsServiceClient.listContacts`.
    func listContacts(
      request: ListContactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse

    /// See `EssentialContactsServiceClient.getContact`.
    func getContact(
      request: GetContactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.Contact

    /// See `EssentialContactsServiceClient.deleteContact`.
    func deleteContact(
      request: DeleteContactRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `EssentialContactsServiceClient.computeContacts`.
    func computeContacts(
      request: ComputeContactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse

    /// See `EssentialContactsServiceClient.sendTestMessage`.
    func sendTestMessage(
      request: SendTestMessageRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.EssentialContactsServiceProtocol {
  public func createContact(request: CreateContactRequest) async throws
    -> GoogleCloudEssentialContactsV1.Contact
  {
    try await self.createContact(request: request, options: .init())
  }

  public func createContact(
    request: CreateContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createContact(
    parent: Swift.String,
    contact: Contact?,
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    let request = CreateContactRequest().with {
      $0.parent = parent
      $0.contact = contact
    }
    return try await self.createContact(request: request)
  }

  public func updateContact(request: UpdateContactRequest) async throws
    -> GoogleCloudEssentialContactsV1.Contact
  {
    try await self.updateContact(request: request, options: .init())
  }

  public func updateContact(
    request: UpdateContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateContact(
    contact: Contact?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    let request = UpdateContactRequest().with {
      $0.contact = contact
      $0.updateMask = updateMask
    }
    return try await self.updateContact(request: request)
  }

  public func listContacts(request: ListContactsRequest) async throws
    -> GoogleCloudEssentialContactsV1.ListContactsResponse
  {
    try await self.listContacts(request: request, options: .init())
  }

  public func listContacts(
    request: ListContactsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.ListContactsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listContactsByItems(
    request: ListContactsRequest
  ) -> some AsyncSequence<Contact, Swift.Error> & Sendable {
    self.listContactsByItems(request: request, options: .init())
  }

  /// Lists the contacts that have been set on a resource.
  ///
  /// @Snippet(path: "EssentialContactsService_ListContacts")
  public func listContactsByItems(
    request: ListContactsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Contact, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudEssentialContactsV1.ListContactsResponse in
      var request = request
      request.pageToken = token
      return try await self.listContacts(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listContactsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Contact, Swift.Error> & Sendable {
    let request = ListContactsRequest().with {
      $0.parent = parent
    }
    return self.listContactsByItems(request: request)
  }

  public func getContact(request: GetContactRequest) async throws
    -> GoogleCloudEssentialContactsV1.Contact
  {
    try await self.getContact(request: request, options: .init())
  }

  public func getContact(
    request: GetContactRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getContact(
    name: Swift.String,
  ) async throws -> GoogleCloudEssentialContactsV1.Contact {
    let request = GetContactRequest().with {
      $0.name = name
    }
    return try await self.getContact(request: request)
  }

  public func deleteContact(request: DeleteContactRequest) async throws {
    try await self.deleteContact(request: request, options: .init())
  }

  public func deleteContact(
    request: DeleteContactRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteContact(
    name: Swift.String,
  ) async throws {
    let request = DeleteContactRequest().with {
      $0.name = name
    }
    try await self.deleteContact(request: request)
  }

  public func computeContacts(request: ComputeContactsRequest) async throws
    -> GoogleCloudEssentialContactsV1.ComputeContactsResponse
  {
    try await self.computeContacts(request: request, options: .init())
  }

  public func computeContacts(
    request: ComputeContactsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudEssentialContactsV1.ComputeContactsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func computeContactsByItems(
    request: ComputeContactsRequest
  ) -> some AsyncSequence<Contact, Swift.Error> & Sendable {
    self.computeContactsByItems(request: request, options: .init())
  }

  /// Lists all contacts for the resource that are subscribed to the
  /// specified notification categories, including contacts inherited from
  /// any parent resources.
  ///
  /// @Snippet(path: "EssentialContactsService_ComputeContacts")
  public func computeContactsByItems(
    request: ComputeContactsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Contact, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudEssentialContactsV1.ComputeContactsResponse in
      var request = request
      request.pageToken = token
      return try await self.computeContacts(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func sendTestMessage(request: SendTestMessageRequest) async throws {
    try await self.sendTestMessage(request: request, options: .init())
  }

  public func sendTestMessage(
    request: SendTestMessageRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }
}
