// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The notification categories that an essential contact can be subscribed to.
/// Each notification will be categorized by the sender into one of the following
/// categories. All contacts that are subscribed to that category will receive
/// the notification.
public enum NotificationCategory: Codable, Equatable, Sendable {
  /// Notification category is unrecognized or unspecified.
  case unspecified
  /// All notifications related to the resource, including notifications
  /// pertaining to categories added in the future.
  case all
  /// Notifications related to imminent account suspension.
  case suspension
  /// Notifications related to security/privacy incidents, notifications, and
  /// vulnerabilities.
  case security
  /// Notifications related to technical events and issues such as outages,
  /// errors, or bugs.
  case technical
  /// Notifications related to billing and payments notifications, price updates,
  /// errors, or credits.
  case billing
  /// Notifications related to enforcement actions, regulatory compliance, or
  /// government notices.
  case legal
  /// Notifications related to new versions, product terms updates, or
  /// deprecations.
  case productUpdates
  /// Child category of TECHNICAL. If assigned, technical incident notifications
  /// will go to these contacts instead of TECHNICAL.
  case technicalIncidents
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .all: return 2
    case .suspension: return 3
    case .security: return 5
    case .technical: return 6
    case .billing: return 7
    case .legal: return 8
    case .productUpdates: return 9
    case .technicalIncidents: return 10
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "NOTIFICATION_CATEGORY_UNSPECIFIED"
    case .all: return "ALL"
    case .suspension: return "SUSPENSION"
    case .security: return "SECURITY"
    case .technical: return "TECHNICAL"
    case .billing: return "BILLING"
    case .legal: return "LEGAL"
    case .productUpdates: return "PRODUCT_UPDATES"
    case .technicalIncidents: return "TECHNICAL_INCIDENTS"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NotificationCategory/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "NOTIFICATION_CATEGORY_UNSPECIFIED": self = .unspecified
    case "ALL": self = .all
    case "SUSPENSION": self = .suspension
    case "SECURITY": self = .security
    case "TECHNICAL": self = .technical
    case "BILLING": self = .billing
    case "LEGAL": self = .legal
    case "PRODUCT_UPDATES": self = .productUpdates
    case "TECHNICAL_INCIDENTS": self = .technicalIncidents
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NotificationCategory/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 2: self = .all
    case 3: self = .suspension
    case 5: self = .security
    case 6: self = .technical
    case 7: self = .billing
    case 8: self = .legal
    case 9: self = .productUpdates
    case 10: self = .technicalIncidents
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .all: return try container.encode(2)
    case .suspension: return try container.encode(3)
    case .security: return try container.encode(5)
    case .technical: return try container.encode(6)
    case .billing: return try container.encode(7)
    case .legal: return try container.encode(8)
    case .productUpdates: return try container.encode(9)
    case .technicalIncidents: return try container.encode(10)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
