// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for the SendTestMessage method.
public struct SendTestMessageRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The list of names of the contacts to send a test message to.
  /// Format: organizations/{organization_id}/contacts/{contact_id},
  /// folders/{folder_id}/contacts/{contact_id} or
  /// projects/{project_id}/contacts/{contact_id}
  public var contacts: [Swift.String] = []

  /// Required. The name of the resource to send the test message for. All
  /// contacts must either be set directly on this resource or inherited from
  /// another resource that is an ancestor of this one. Format:
  /// organizations/{organization_id}, folders/{folder_id} or
  /// projects/{project_id}
  public var resource: Swift.String = Swift.String()

  /// Required. The notification category to send the test message for. All
  /// contacts must be subscribed to this category.
  public var notificationCategory: NotificationCategory = NotificationCategory()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SendTestMessageRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SendTestMessageRequest().with { $0.contacts = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let contacts = CodingKeys(stringValue: "contacts")
    static let resource = CodingKeys(stringValue: "resource")
    static let notificationCategory = CodingKeys(stringValue: "notificationCategory")

    static let _knownKeys: Set<Swift.String> = [
      "contacts",
      "resource",
      "notificationCategory",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .contacts) {
      self.contacts = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
      self.resource = value
    }
    if let value = try container.decodeIfPresent(
      NotificationCategory.self, forKey: .notificationCategory)
    {
      self.notificationCategory = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.contacts, forKey: .contacts)
    try container.encode(self.resource, forKey: .resource)
    try container.encode(self.notificationCategory, forKey: .notificationCategory)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.essentialcontacts.v1.SendTestMessageRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
