// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the SendTestMessage method.
public struct SendTestMessageRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The list of names of the contacts to send a test message to.
  /// Format: organizations/{organization_id}/contacts/{contact_id},
  /// folders/{folder_id}/contacts/{contact_id} or
  /// projects/{project_id}/contacts/{contact_id}
  public var contacts: [Swift.String] = []

  /// Required. The name of the resource to send the test message for. All
  /// contacts must either be set directly on this resource or inherited from
  /// another resource that is an ancestor of this one. Format:
  /// organizations/{organization_id}, folders/{folder_id} or
  /// projects/{project_id}
  public var resource: Swift.String = Swift.String()

  /// Required. The notification category to send the test message for. All
  /// contacts must be subscribed to this category.
  public var notificationCategory: NotificationCategory = NotificationCategory()

  /// Initialize a new instance of `SendTestMessageRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SendTestMessageRequest().with { $0.contacts = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.essentialcontacts.v1.SendTestMessageRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
